
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package naturaltosql.compiler;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int TK_ENTERO = 22;
  public static final int TK_TABLA_ESTUDIANTE = 17;
  public static final int TK_CREAR_TABLA = 2;
  public static final int TK_REAL = 23;
  public static final int TK_LISTAR = 4;
  public static final int TK_FIN_SENTENCIA = 9;
  public static final int TK_ENTERO_DEFINICION = 18;
  public static final int TK_MAYOR_IGUAL = 26;
  public static final int TK_MENOR = 25;
  public static final int TK_CADENA = 21;
  public static final int TK_ATRIBUTOS = 3;
  public static final int TK_NOMBRE = 10;
  public static final int TK_BORRAR = 6;
  public static final int TK_IGUAL = 28;
  public static final int TK_CADENA_DEFINICION = 20;
  public static final int TK_CARRERA = 14;
  public static final int TK_Y = 31;
  public static final int TK_TODOS = 16;
  public static final int TK_PROMEDIO = 12;
  public static final int TK_MENOR_IGUAL = 27;
  public static final int TK_REAL_DEFINICION = 19;
  public static final int EOF = 0;
  public static final int TK_O = 30;
  public static final int TK_DIFERENTE = 29;
  public static final int error = 1;
  public static final int TK_DONDE = 8;
  public static final int TK_MAYOR = 24;
  public static final int TK_COMA = 15;
  public static final int TK_ACTUALIZAR = 7;
  public static final int TK_INSERTAR = 5;
  public static final int TK_CARNET = 11;
  public static final int TK_TELEFONO = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_CREAR_TABLA",
  "TK_ATRIBUTOS",
  "TK_LISTAR",
  "TK_INSERTAR",
  "TK_BORRAR",
  "TK_ACTUALIZAR",
  "TK_DONDE",
  "TK_FIN_SENTENCIA",
  "TK_NOMBRE",
  "TK_CARNET",
  "TK_PROMEDIO",
  "TK_TELEFONO",
  "TK_CARRERA",
  "TK_COMA",
  "TK_TODOS",
  "TK_TABLA_ESTUDIANTE",
  "TK_ENTERO_DEFINICION",
  "TK_REAL_DEFINICION",
  "TK_CADENA_DEFINICION",
  "TK_CADENA",
  "TK_ENTERO",
  "TK_REAL",
  "TK_MAYOR",
  "TK_MENOR",
  "TK_MAYOR_IGUAL",
  "TK_MENOR_IGUAL",
  "TK_IGUAL",
  "TK_DIFERENTE",
  "TK_O",
  "TK_Y"
  };
}

